### ISSUE TITLE
Don't offer sync until after user interacts with dialog

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/security-advisor-shield-study#23]
We ultimately want people to change there passwords and be safer. For both branches (offering sync with current features/sync with automatic notifications) we should wait until the user confirms "yes, I've updated my password" or "I don't have a password." After that, we should show a "Congrats. You're safer now" dialog and then present the sync offer. I'd say the sync offer stays open until the user clicks out of the panel.

@gregglind - any issues with that?

**Comment by casebenton** [comment]
Markus' UI also uses this, and I've merged it in with #25
