### ISSUE TITLE
Cannot `jpm run` with Firefox 48

### ISSUE THREAD

**Issue by Osmose** [mozilla/security-advisor-shield-study#43]
I cannot test the add-on via `jpm run` on Firefox 48, branded or unbranded. Firefox launches with the following error:

```
JPM [info] Starting jpm run on Security Advisor
JPM [info] Creating a new profile
1472163387955  	addons.xpi     	WARN   	Add-on @security-advisor is not correctly signed.
1472163387956  	addons.xpi     	WARN   	Add-on @security-advisor is not correctly signed.
```

**Comment by gregglind** [comment]
I claim unbranded 48 _should_ work.

```
npm install -g get-firefox
get-firefox -cb unbranded-release
```

**Comment by mythmon** [comment]
This is also working for me, using an unbranded build from http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1469543944/firefox-48.0.en-US.linux-x86_64-add-on-devel.tar.bz2.

**Comment by mythmon** [comment]
Closing since we can't seem to reproduce.

**Comment by Osmose** [comment]
Weird, Benton was able to reproduce the issue as well when I first noticed it.

**Comment by Osmose** [comment]
I have since discovered that my unbranded copy of Firefox was replaced by a branded copy of Firefox, potentially due to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290548

Either way, I re-downloaded a new unbranded copy and things worked fine. Sorry for the confusion!

**Comment by Christos-Papoulas** [comment]
I have the same problem with Firefox 49.0.1, before the update everything worked fine. How can overcome this issue?

**Comment by sentryone** [comment]
I am having the same problem in Firefox 49.0.1, and previous add-on worked fine. Any ideas will be appreciated.

**Comment by mythmon** [comment]
@Christos-Papoulas @sentryone: Since upgrades from unbranded versions of Firefox 48 to 49 for a while was converting them to branded versions, can you try and download a fresh, unbranded version of Firefox [from here](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) and trying again?

**Comment by sentryone** [comment]
Actually just got a tip from someone and if I downloaded Firefox Nightly it worked:

> jpm run -b Nightly

Thank you for your input!

**Comment by vanilla-thunder** [comment]
this whole add-on development thing is the worst documented crap I have ever seen.
Many tutorials seem to be outdated and do not work anymore.  When installing "Unbranded Release" you get "Developer Preview", but when you start it, you get "Firefox Nightly". JPM crap tries to load 32bit executable though 64bit version is installed. Debugging Addons is pain in the ass; run, restart, new profile each time, multiple versions, close, edit, run again. Add-on not signed, disabled, run another version. Repeat 100 times.
Why so complicated? 
Developing and Debugging Chrome Plugins:
check "developer mode" setting and drag&drop your module directory into chrome. You are ready to go. No useless JPM crap, add-on signing, registering api credentials or 5 different browser version. 
What kind of sadistic person came up with such a marvelous idea?

**Comment by mo8la** [comment]
Thank "mythmon"

`jpm -b "C:\Program Files (x86)\Mozilla Developer Preview\firefox.exe" run`
