### ISSUE TITLE
Add-on seems to break if I disable then re-enable via about:addons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/security-advisor-shield-study#51]
Found in b6f5565 (via `git rev-parse --short HEAD`).

### Steps to reproduce:
1. Git clone repo.
1. `$ npm install`
1. `$ npm run build`
1. `$ jpm run -b Aurora` (or if you don't have a global JPM installed, try `$ ./node_modules/.bin/jpm run -b Aurora`).
1. Go to http://www.adobe.com and verify the alert appears in address bar.
1. Go to about:addons and select Security Advisor.
1. Press Disable to disable add-on.
1. Press Enable to re-enable add-on.
1. Look at your Terminal window.
1. Go to http://www.adobe.com and verify the alert still reappears after re-enabling.

### Actual results:

```sh
$ ./node_modules/.bin/jpm run -b Aurora
JPM [info] Starting jpm run on Security Advisor
JPM [info] Creating a new profile

1475710024402  	addons.xpi     	ERROR  	Attempted to load bootstrap scope from missing directory /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/06bf11d1-4b5b-4c24-ac98-f5af52e5021f/extensions/@security-advisor.xpi
1475710024402  	addons.xpi     	WARN   	Add-on @security-advisor is missing bootstrap method startup
1475710024406  	addons.xpi     	WARN   	No XPIState for @security-advisor in app-profile
```

The add-on seems to not work after re-enabling it.

---

#### Before:

![about_config](https://cloud.githubusercontent.com/assets/557895/19135352/d8d5cb86-8b18-11e6-9ccd-3ff9463b6a6e.png)

#### After:

![about_config](https://cloud.githubusercontent.com/assets/557895/19135361/f6233a5c-8b18-11e6-80fa-412b0246feaa.png)

**Comment by pdehaan** [comment]
Not sure if this is because I'm running via `jpm run -b Aurora` versus another method and disabling and reenabling changes some temp folder.

**Comment by pdehaan** [comment]
![index_of_jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_c43465fa-9586-4ac4-bb41-a0ef7886a745_extensions__security-advisor_xpi__](https://cloud.githubusercontent.com/assets/557895/19135683/59df8c4c-8b1b-11e6-8e2f-9f5a9fc8e67d.png)

**Comment by Osmose** [comment]
Thanks for the report!

I'm unable to get past Step 8, as once I click disable, the add-on is automatically uninstalled, which is expected behavior. I'm testing on the latest Dev Edition on OSX.

@pdehaan Can you confirm that the add-on does not disappear from the add-on list when you disable it?

**Comment by gregglind** [comment]
(Echoing that it SHOULD be that disable uninstalls.  Odd!)

**Comment by pdehaan** [comment]
Actually now it seems to uninstall the add-on when I disable the add-on in **about:addons**.
Although it also opens a new tab: https://www.mozilla.org/en-US/?fxVersion=51.0a2&reason=user-ended-study&updateChannel=aurora&variation=auto-open-panel&who=unknown&xname=Security+Advisor+Test

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19329097/deb4e74e-908b-11e6-9993-53ed3dd42305.png)
